on:
  push:
    branches:
      - main

name: Deploy to AWS

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: |
          npm install serverless -g
          yarn install

      - name: Deploy to Lambda & API Gateway
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
